### ISSUE TITLE
entry updated time is showing in UTC-0 instead of local time

### ISSUE THREAD

**Issue by mujeebcpy** [samihsoylu/journal#30]
entry updated time is UTC-0, not current country local time. it would be great if it automatically choose the timezone or change from settings.

**Comment by samihsoylu** [comment]
It sounds like an interesting idea to have each user to be able to choose their own timezone from the preferences. I will look into this :)

**Comment by samihsoylu** [comment]
Hi @mujeebcpy 

You can now select your own timezone if you upgrade to journal v1.5.0. Please follow the [upgrade guide](https://samihsoylu.notion.site/Upgrading-04fcbde744c244bcacad577604c43b41) in order to avoid any problems.

Should you encounter any issues, don't hesitate to reach out. I am also on [Discord](https://discord.gg/bfkMjU5teE).
