### ISSUE TITLE
Any way to mark an entry as completed?

### ISSUE THREAD

**Issue by murty2** [samihsoylu/journal#39]
Any way to mark an entry as completed? For example, display a link "Mark as complete" at the bottom of each entry (unless its already marked complete) and when click that link the string "[Done]" must be inserted at the beginning of the entry title. The dashboard should hide all entries with titles beginning with the string "[Done]"

Is this possible?

**Comment by samihsoylu** [comment]
Hi @murty2 

I can see how that could be handy for tracking tasks, but Journal is designed more as a simple, private logbook rather than a task manager. So, features like marking entries as complete or automatically hiding them aren't something it supports right now.

That said, I really appreciate the feedback and will keep it in mind for future updates! In the meantime, you can use categories to organize your entries and separate completed tasks as a workaround.

Thanks for sharing your thoughts, and feel free to reach out with any more ideas or questions!
